require 'options'
require 'keymaps'

require 'plugins.go'
require 'plugins.which-key'
require 'plugins.gruvbox'
require 'plugins.mini'
require 'plugins.snacks'
require 'plugins.blink-cmp'
require 'plugins.lspconfig'
require 'plugins.conform'
require 'plugins.treesitter'
require 'plugins.zellij-nav'
